name: client_tools
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.4.0-282.2.beta

dependencies:
  flutter:
    sdk: flutter
  const_date_time: ^1.1.0
  http: ^1.2.1
  shared_preferences: ^2.2.2

  tools:
    path: ../tools

dev_dependencies:
  build_runner: ^2.0.3
  flutter_gen_runner: ^5.2.0
  lints: ^3.0.0
  test: ^1.24.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/colleges/

  # fonts:
  #   - family: NotoSansSC
  #     fonts:
  #       - asset: assets/fonts/NotoSansSC-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/NotoSansSC-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/NotoSansSC-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/NotoSansSC-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/NotoSansSC-Light.ttf
  #         weight: 300

flutter_gen:
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
  output: lib/src/ui/generated/
  # line_length: 80

  # integrations:
  #   flutter_svg: true
